#!/bin/bash

# Template to add new update scripts from CVS for a specific tool
#
# Author: Raul Siles (raul _AT_ raulsiles _DOT_ com)
# Date: October 2009
# Version: 0.1
#
# Usage:
# 0. Copy this template to /usr/bin/samurai_svn/scripts as cvs_TOOL-NAME.sh,
#    replacing TOOL-NAME by the name of the tool (eg. cvs_DirBuster.sh)
#    $ cp cvs_template ../scripts/cvs_DirBuster.sh
# 1. Change the permissions of the new script to 755:
#    $ chmod 755 /usr/bin/samurai_svn/scripts/cvs_DirBuster.sh
# 2. Edit the new script file...
# 3. Replace the TOOL variable below with the tool name
#    eg. TOOL=DirBuster
# 4. Replace the CVS variable below with the reference to the CVS repository,
#    that is, with the value for the cvs "-d" option
#    eg. CVS=pserver:anonymous@dirbuster.cvs.sourceforge.net:/cvsroot/dirbuster
# 5. Create a new CVS update menu pointing to this new CVS update script
# 6. Include any other commands specific for this tool under the "Additional 
#    instructions/actions" section (at the end), such as how to build or 
#    compile the tool from the CVS source code
#

# Tool name
TOOL="Add the tool name here"

# CVS repository
CVS="Add the CVS repository here"

# Main dir
DIR=/usr/bin/samurai_svn

# CVS update script
CVS_UPDATE=$DIR/bin/cvs_update.sh

# Launch the update
$CVS_UPDATE $TOOL $CVS

# Additional instructions/actions
# ...


